# configuration file for reivew analysis
path:
    # review data from from http://jmcauley.ucsd.edu/data/amazon/index.html
    #   there are much larger sets and you're free to experiment on your own!
    # R. He, J. McAuley. "Modeling the visual evolution of fashion trends
    #    with one-class collaborative filtering." WWW, 2016
    # J. McAuley, C. Targett, J. Shi, A. van den Hengel. "Image-based
    #     recommendations on styles and substitutes". SIGIR, 2015
    # http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/
    raw: data/reviews_Office_Products_10.json.gz # reviews_Amazon_Instant_Video_5.json.gz (alternate)
    metadata: data/meta_Office_Products.json.gz # meta_Amazon_Instant_Video.json.gz (alterate)
    example: data/data_train_example.csv  # substitute as x or y
    etl: data/data_etl.pkl.gz # transformed features
    model_preproc: data/model_preproc.pkl.gz  # ETL options for new data
    model_classifier: data/model_classifier.pkl.gz  # classifiers for ananlysis
    figure_classifier: data/model_classifier.png  # performance on training set
    sentiment: data/data_etl_sentiment.pkl.gz  # sentiment scores aligned with ETL samples
    model_fused: data/model_sentiment_fused.pkl.gz  # classifiers for fused analysis
    figure_fused: data/model_sentiment_fused.png  # performance on training set

# configuration options for part 0, ETL
partition:
    test: 0.2   # train=80%, test=20%
    validation: 0.2   # train_all=80%, train_validation=20%
encoding:
    max_text_terms: 300  # number of features for simple TF/IDF tokenization
    
# configuration for baseline - model2
training:
    scoring: [average_precision, f1_micro, f1_macro, roc_auc, accuracy]   # many scoring metrics, FIRST is the "best" scoring
    threads: 2
    cross_validate: False
    model_type: gbm  # look at `baseline` script, can be one of: rf, bayes, gbm

# configuration for wrapping of models - model2+ model3
publish:
    api_token: # <ATTUID>:<API TOKEN> # your-user-token-code
    name_model2: model2b-review-text
    name_model3: model3-setiment-ex
    url_model: http://acumosr-test.research.att.com:8090/onboarding-app/v2/models    # to the workshop instance
    # url_model: http://acumos.research.att.com:8090/onboarding-app/v2/models    # to a "production" instance
    url_auth: http://acumosr-test.research.att.com:8090/onboarding-app/v2/auth    # to the workshop instance
    # url_auth: http://acumos.research.att.com:8090/onboarding-app/v2/auth    # to a "production" instance

# configuration calling sentiment models - model 3
sentiment:
    deploy_host: "http://acumos-gpu.research.att.com"
    active_model: [yelp, care, twitter]    # can hold multiple active models
    twitter:
        port: 8764
        path: data/sentiment_etl_twitter.csv.gz
        ref: http://acumos.research.att.com/index.html#/marketSolutions?solutionId=58d34454-ff82-4ce0-aee0-8ffde3600f5c&revisionId=32ddae2a-d8e0-4d9b-8c86-ed796b2616c4%23md-model-detail-template#md-model-detail-template
        api: sent_predict
        style: text-to-float
    yelp:
        port: 8760
        path: data/sentiment_etl_yelp.csv.gz
        ref: http://acumos.research.att.com/index.html#/marketSolutions?solutionId=ff468e3c-86da-412d-88cb-8c816f2ac27f&revisionId=c9c89cda-3748-4e73-9502-f9cf161ab107#md-model-detail-template
        api: sent_predict
        style: text-to-float  # string input, multiple float output
    mobility:
        port: 8761
        path: data/sentiment_etl_mobility.csv.gz
        ref: http://acumos.research.att.com/index.html#/marketSolutions?solutionId=e9b0463c-fd2a-48ef-babd-1c1b188f820f&revisionId=2ad76136-ad2e-48aa-887c-df043f382f2c#md-model-detail-template
        api: sent_predict
        style: text-to-float  # string input, multiple float output
    dtv: 
        port: 8762
        ref: http://acumos.research.att.com/index.html#/marketSolutions?solutionId=642d31e6-2e29-4cc7-9ae9-2f574ccc6f5a&revisionId=5e204277-b2c4-4342-83b6-804f09fc9bfa%23md-model-detail-template#md-model-detail-template
        api: sent_predict
        style: text-to-float  # string input, multiple float output
        path: data/sentiment_etl_dtv.csv.gz
    care:
        port: 8763
        path: data/sentiment_etl_care.csv.gz
        ref: http://acumos.research.att.com/index.html#/marketSolutions?solutionId=ff6581b1-30d5-49f8-8962-0e42865ddd33&revisionId=26dfddd6-a345-4749-8a79-e278f779c5ab%23md-model-detail-template#md-model-detail-template
        api: classify
        style: text-to-float  # string input, multiple float output
        
    
    
    
    
    