# configuration file for reivew analysis
path:
    # review data from from http://jmcauley.ucsd.edu/data/amazon/index.html
    #   there are much larger sets and you're free to experiment on your own!
    # R. He, J. McAuley. "Modeling the visual evolution of fashion trends
    #    with one-class collaborative filtering." WWW, 2016
    # J. McAuley, C. Targett, J. Shi, A. van den Hengel. "Image-based
    #     recommendations on styles and substitutes". SIGIR, 2015
    # http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/
    raw: data/reviews_Office_Products_10.json.gz # reviews_Amazon_Instant_Video_5.json.gz (alternate)
    metadata: data/meta_Office_Products.json.gz # meta_Amazon_Instant_Video.json.gz (alterate)
    example: data/data_train_example.csv  # substitute as x or y
    etl: data/data_etl.pkl.gz # transformed features
    model_preproc: data/model_preproc.pkl.gz  # ETL options for new data
    model_classifier: data/model_classifier.pkl.gz  # classifiers for ananlysis
    model_embedding: data/model_embedding.pkl.gz

# configuration options for part 0, ETL
partition:
    test: 0.2   # train=80%, test=20%
    validation: 0.2   # train_all=80%, train_validation=20%
encoding:
    max_text_terms: 300  # number of features for simple TF/IDF tokenization
    
# configuration for baseline
training:
    scoring: [average_precision, f1_micro, f1_macro, roc_auc, accuracy]   # many scoring metrics, FIRST is the "best" scoring
    threads: 2
    cross_validate: False
    model_type: rf  # look at `baseline` script, can be one of: rf, bayes, gbm

